# Generated by Django 3.2 on 2021-05-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_1m_concent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('concentrate', models.CharField(choices=[('C', 'concentrate'), ('P', 'play'), ('U', 'unknown')], max_length=2)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
