# Generated by Django 3.2 on 2021-05-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_remove_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('daily_concent_hour', models.FloatField(null=True)),
                ('daily_tot_hour', models.FloatField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_ana_uid', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_1m_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('concentrate', models.CharField(choices=[('C', 'Concentrate'), ('P', 'Play'), ('U', 'Unknown')], max_length=2, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_1m_uid', to='api.user')),
            ],
        ),
    ]
