# Generated by Django 3.2 on 2021-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_analysis',
            name='daily_concent_hour',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='study_analysis',
            name='daily_tot_hour',
            field=models.FloatField(default=0, null=True),
        ),
    ]
