# Generated by Django 3.2 on 2021-05-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210519_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_analysis',
            name='daily_concent_hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='study_analysis',
            name='daily_tot_hour',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
