# Generated by Django 3.2 on 2021-05-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_user'),
        ('study', '0008_one_week_study_data_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='today_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_date_uid', to='api.user')),
            ],
        ),
    ]
