# Generated by Django 3.2 on 2021-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='badge',
            field=models.CharField(choices=[('B', 'BRONZE'), ('S', 'SILVER'), ('G', 'GOLD'), ('P', 'PLATINUM'), ('D', 'DIAMOND')], default='B', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='birth',
            field=models.DateField(null=True, verbose_name='Birth'),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='PassWord'),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('N', '설정안함(None)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tot_concent_hour',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Study Hour'),
        ),
        migrations.AddField(
            model_name='account',
            name='uid',
            field=models.EmailField(default='', max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='NickName'),
        ),
    ]
