# Generated by Django 3.2 on 2021-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210505_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='NickName'),
        ),
    ]
