# Generated by Django 3.2 on 2021-05-05 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210505_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('B', 'BRONZE'), ('S', 'SILVER'), ('G', 'GOLD'), ('P', 'PLATINUM'), ('D', 'DIAMOND')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(verbose_name='Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('N', '설정안함(None)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='tot_concent_hour',
            field=models.IntegerField(default=0, verbose_name='Total Study Hour'),
        ),
    ]
