# Generated by Django 3.2 on 2021-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210505_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('B', 'BRONZE'), ('S', 'SILVER'), ('G', 'GOLD'), ('P', 'PLATINUM'), ('D', 'DIAMOND')], default='B', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, verbose_name='Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('N', '설정안함(None)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tot_concent_hour',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Study Hour'),
        ),
    ]
