# Generated by Django 3.2 on 2021-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('N', 'NULL'), ('B', 'BRONZE'), ('S', 'SILVER'), ('G', 'GOLD'), ('P', 'PLATINUM'), ('D', 'DIAMOND')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
