# Generated by Django 3.2 on 2021-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_like_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
