# Generated by Django 3.2 on 2021-05-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_remove_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_tdl',
            fields=[
                ('m_todo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stt_date', models.DateField()),
                ('end_date', models.DateField()),
                ('m_content', models.TextField(max_length=100)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monthly_tdl_uid', to='api.user')),
            ],
        ),
    ]
