# Generated by Django 3.2 on 2021-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0002_weekly_tdl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_tdl',
            name='m_todo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weekly_tdl',
            name='w_todo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
