# Generated by Django 3.2 on 2021-05-14 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_user'),
        ('tdl', '0003_auto_20210512_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_tdl',
            fields=[
                ('d_todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_date', models.DateField()),
                ('d_tag', models.TextField(max_length=20)),
                ('d_content', models.TextField(max_length=100)),
                ('d_check', models.BooleanField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Daily_tdl_uid', to='api.user')),
            ],
        ),
    ]
