# Generated by Django 3.2 on 2021-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0004_daily_tdl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tdl',
            name='d_tag',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
