# Generated by Django 3.2 on 2021-06-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0005_alter_daily_tdl_d_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tdl',
            name='d_content',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_tdl',
            name='m_content',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_tdl',
            name='w_content',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
