# Generated by Django 3.2 on 2021-07-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('maxppl', models.IntegerField(default=2)),
                ('is_secret', models.BooleanField()),
                ('room_pwd', models.CharField(max_length=10, null=True)),
                ('room_tag', models.CharField(max_length=50, null=True)),
                ('room_comment', models.CharField(max_length=2000, null=True)),
                ('room_color', models.CharField(max_length=10, null=True)),
                ('maker_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_maker', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField()),
                ('room_color', models.CharField(max_length=10)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_room', to='main.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_uid', to='api.user')),
            ],
        ),
    ]
