# Generated by Django 2.2 on 2021-09-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210720_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_enroll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
