# Generated by Django 2.2 on 2021-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210905_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_enroll',
            name='current',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
