# Generated by Django 2.2 on 2021-09-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210926_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_room',
            name='room_array',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
    ]
